src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Symfony\Component\Validator\Constraints\NotBlank;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    #[ORM\Column(name: 'email', type: 'string', length: 255, unique: true)]
    #[Assert\Email]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $phone_number = null;
    #[Assert\NotBlank]
    #[Assert\Unique]
    #[Assert\Length(min: 3)]
    #[Assert\Length(max: 255)]
    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    /**
     * @var Collection<int, Activity>
     */
    #[ORM\ManyToMany(targetEntity: Activity::class, mappedBy: 'registered')]
    private Collection $activities;
    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Campus $Campus = null;
    #[Assert\Length(max: 255)]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fileName = null;

    #[ORM\Column]
    private ?bool $isActive = null;

    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    public function __construct()
    {
        $this->activities = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * @return Collection<int, Activity>
     */
    public function getActivities(): Collection
    {
        return $this->activities;
    }

    public function addActivity(Activity $activity): static
    {
        if (!$this->activities->contains($activity)) {
            $this->activities->add($activity);
            $activity->addInscrit($this);
        }

        return $this;
    }

    public function removeActivity(Activity $activity): static
    {
        if ($this->activities->removeElement($activity)) {
            $activity->removeInscrit($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Activity>
     */
    public function getActivitiesOwner(): Collection
    {
        return $this->ActivitiesOwner;
    }

    public function addActivitiesOwner(Activity $activitiesOwner): static
    {
        if (!$this->ActivitiesOwner->contains($activitiesOwner)) {
            $this->ActivitiesOwner->add($activitiesOwner);
            $activitiesOwner->setOrganizer($this);
        }

        return $this;
    }

    public function removeActivitiesOwner(Activity $activitiesOwner): static
    {
        if ($this->ActivitiesOwner->removeElement($activitiesOwner)) {
            // set the owning side to null (unless already changed)
            if ($activitiesOwner->getOrganizer() === $this) {
                $activitiesOwner->setOrganizer(null);
            }
        }

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->Campus;
    }

    public function setCampus(?Campus $Campus): static
    {
        $this->Campus = $Campus;

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function setFileName(?string $fileName): static
    {
        $this->fileName = $fileName;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->isActive;
    }

    public function setActive(bool $isActive): static
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function convertToJson()
    {
        return json_encode([
            'id' => str_replace(" ", "&@^", $this->getId()),
            'email' => str_replace(" ", "&@^", $this->getEmail()),
            'roles' => str_replace(" ", "&@^", $this->getRoles()),
            'phone_number' => str_replace(" ", "&@^", $this->getPhoneNumber()),
            'pseudo' => str_replace(" ", "&@^", $this->getPseudo()),
            'fileName' => str_replace(" ", "&@^", $this->getFileName()),
            'isActive' => str_replace(" ", "&@^", $this->isActive()),
            'lastName' => str_replace(" ", "&@^", $this->getLastName()),
            'firstName' => str_replace(" ", "&@^", $this->getFirstName()),
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;


use App\Entity\User;
use App\Form\CsvImport;
use App\Form\UserType;
use App\Form\UserUpdateType;
use App\Repository\UserRepository;
use App\Repository\ActivityRepository;
use App\Security\UserProvider;
use App\Service\CsvImportService;
use App\Service\FileUploaderService;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Exception\ORMException;
use Doctrine\ORM\OptimisticLockException;
use PhpParser\Node\Scalar\MagicConst\File;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\String\Slugger\SluggerInterface;


class UserController extends AbstractController
{

    public function __construct(
        private MailerInterface             $mailer,
        private UserRepository              $userRepository,
        private Security                    $security,
        private CsvImportService            $csvImportService,
        private FileUploaderService         $fileUploaderService,
        private ActivityRepository          $activityRepository,
        private EntityManagerInterface      $entityManager,
        private UserPasswordHasherInterface $passwordHasher,
    )
    {
    }

    #[IsGranted("ROLE_USER")]
    #[Route(path: '/profil', name: 'app_profile')]
    public function profile(): Response
    {
        $activites = $this->activityRepository->findByCreator($this->getUser());

        return $this->render('user/profile.html.twig', [
            'activities' => $activites,
            'user' => $this->getUser(),
        ]);
    }

    #[IsGranted("ROLE_USER")]
    #[Route(path: '/profil/search/{id}', name: 'app_profile_view')]
    public function profileView(int $id): Response
    {
        $userSearch = $this->userRepository->find($id);
        $activitesSearch = $this->activityRepository->findByCreator($userSearch);

        return $this->render('user/profileView.html.twig', [
            'user' => $userSearch,
            'activities' => $activitesSearch,
        ]);
    }

    #[IsGranted("ROLE_ADMIN")]
    #[Route(path: '/profil/create', name: 'app_user_create')]
    public function create(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            if (!$this->userRepository->findBy(['email' => $user->getEmail()])) {
                /*  set default PictureFileName on Entity */
                if ($form->get("password")->getData() != null && $form->get("passwordConfirm")->getData() != null) {
                    if ($form->get("password")->getData() !== $form->get("passwordConfirm")->getData()) {
                        $hashedPassword = $this->passwordHasher->hashPassword(
                            $user,
                            "password"
                        );
                        $user->setPassword($hashedPassword);
                    } else {
                        $hashedPassword = $this->passwordHasher->hashPassword(
                            $user,
                            $form->get("password")->getData()
                        );
                        $user->setPassword($hashedPassword);
                    }
                }
                $user->setActive(true);
                if ($form->get("profilePicture")->getData() != null) {
                    $user->setFileName($this->fileUploaderService->upload('profilePictures', $form->get('profilePicture')->getData()));
                } else {
                    $user->setFileName("default.jpg");
                }
                $this->entityManager->persist($user);
                $this->entityManager->flush();
                return $this->redirectToRoute('app_profil_list');
            }

        }
        return $this->render('user/profileCreate.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[IsGranted("ROLE_ADMIN")]
    #[Route(path: '/profil/list', name: 'app_profil_list')]
    public function profileList(Request $request): Response
    {
        $form = $this->createForm(CsvImport::class, new File());
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $csvFile = $this->fileUploaderService->upload("csv", $form->get("fileName")->getData());
            $results = $this->csvImportService->importCsv("csv/" . $csvFile);
            if (!empty($results['errors'])) {
                foreach ($results['errors'] as $error) {
                    $this->addFlash('error', $error);
                }
            }
            return $this->redirectToRoute('app_profil_list');
        }

        return $this->render('user/profileList.html.twig', [
            'form' => $form->createView(),
            'users' => $this->userRepository->findAll(),
        ]);
    }

    /**
     * @throws TransportExceptionInterface
     */
    #[IsGranted("ROLE_ADMIN")]
    #[Route(path: '/profil/delete/{id}', name: 'app_user_delete')]
    public function deleteUser(int $id): Response
    {
        $user = $this->userRepository->find($id);
        $email = (new Email())
            ->from('noreply@blizzfull.fr')
            ->to($user->getEmail())
            ->subject('Compte ENI-BDE supprimé')
            ->text('Votre compte ENI-BDE a été supprimé')
            ->html('<p>Votre compte ' . $user->getPseudo() . 'ENI-BDE a été supprimé</p>');
        try {
            $this->mailer->send($email);
        } catch (\Exception $e) {
        }
        $this->userRepository->removeAllRelations($user);
        $this->entityManager->flush();
        return $this->redirectToRoute("app_profil_list");
    }

    #[IsGranted("ROLE_ADMIN")]
    #[Route(path: '/profil/desactivate/{id}', name: 'app_user_desactivate')]
    public function desactivateUser(int $id): Response
    {
        $user = $this->userRepository->find($id);
        $user->setActive(!$user->isActive());
        $this->entityManager->persist($user);
        $this->entityManager->flush();
        return $this->redirectToRoute("app_profil_list");
    }


    /**
     * @throws OptimisticLockException
     * @throws ORMException
     */
    #[IsGranted("ROLE_USER")]
    #[Route(path: '/profileEdit', name: 'app_profile_edit')]
    public function edit(Request $request, SluggerInterface $slugger): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(UserUpdateType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $profilePicture = $form->get('profilePicture')->getData();
            /* Upload file using fileUploader Service + set PictureFileName on Entity*/
            if ($form->get("password")->getData() != null && $form->get("passwordConfirm")->getData() != null) {
                if ($form->get("password")->getData() === $form->get("passwordConfirm")->getData()) {
                    $user->setPassword($this->passwordHasher->hashPassword($user, $form->get("password")->getData()));
                    $this->entityManager->persist($user);
                    $this->entityManager->flush();
                }
            }
            if ($profilePicture) {
                $user->setFileName($this->fileUploaderService->upload("thumbnails", $profilePicture));
            }
            $this->entityManager->persist($user);
            $this->entityManager->flush();
            return $this->redirectToRoute('app_profile');
        }

        return $this->render('user/profileEdit.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/user/profile.html.twig
{% include 'base_logged.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="/styles/home.css">
    <link rel="stylesheet" href="/styles/profil.css">
{% endblock %}

{% block body %}
<div class="myContent">
    <div class="box">
        <h2>Vos informations</h2>
        <div class="separator"></div>
        <img src="{{ asset('profilePictures/'~ user.fileName) }}" class="profilPicture" alt="ProfilePicture">
        <p class="text title">{{user.pseudo}}</p>
        <p class="text email">{{user.email}}</p>
        <div class="more-information">
            <h2>Plus d’information</h2>
            <div class="separator"></div>
            <div class="myInformation">
                <p><span class="information-title">Téléphone : </span>{{user.phoneNumber}}</p>
                <p><span class="information-title">Campus : </span>{{user.campus.name}}</p>
            </div>
            <div class="myInformation">
                <p><span class="information-title">Nom : </span>{{user.lastName}}</p>
                <p><span class="information-title">Prénom : </span>{{user.firstName}}</p>
            </div>
        </div>
        <a href={{path("app_profile_edit")}} class="profile-button modifyProfil"><button class="button">Modifier le compte</button></a>
    </div>
    <div class="box right">
        <h2>Vos sorties proposé</h2>
        <div class="separator"></div>
        <a href={{path("app_activity_create")}} class="profile-button createActivity"><button class="button">Créer une nouvelle sortie</button></a>
        <div class="activity-content" id="activityContent">
            {% for activity in activities %}
                {% if activity.state.id != 6 %}
                <div class="activity" data-lat="{{ activity.lieu.latitude }}" data-long="{{ activity.lieu.longitude }}" data-id="{{ activity.id }}">
                    <span class="flex">
                        <img src={{ asset('thumbnails/' ~ activity.fileName) }} alt="activity thumbnails"/>
                        <span class="title-description">
                            <p class="title">{{ activity.name }}</p>
                            <p class="description">{{ activity.description }}</p>
                        </span>
                    </span>
                    <span class="information">
                        <span class="information_text">
                            <p>Date limite d'inscription : {{ activity.registrationDateLimit|date('Y-m-d') }}</p>
                            <p>Nombre de places : {{ activity.nbLimitParticipants - activity.registered|length }}</p>
                        </span>
                        <span class="buttons">
                            {% if activity.organizer == user and activity.state.code == "ACT_CR" %}
                                <a href="{{ path("activity_update", { 'id': activity.id }) }}">
                                    <button class="button modify"><span>Modifier</span></button>
                                </a>
                                <a href="{{ path("app_cancel_activity", {'id': activity.id}) }}">
                                    <button class="button cancel"><span>Annuler</span></button>
                                </a>
                            {% endif %}
                            {% if activity not in user.activities and activity.state.code == "ACT_EN_C" %}
                                <button class="status cancel" disable>En cour</button>
                            {% endif %}
                            {% if activity not in user.activities and activity.state.code == "ACT_INS_F" %}
                                <button class="status status-close" disable>Fermé</button>
                            {% endif %}
                            {% if activity not in user.activities and activity.state.code == "ACT_TER" %}
                                <button class="status status-cancel" disable>Terminé</button>
                            {% endif %}
                            {% if activity not in user.activities and activity.state.code == "ACT_ANN" %}
                                <button class="status status-cancel" disable>Annulé</button>
                            {% endif %}
                        </span>
                    </span>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/user/profileCreate.html.twig
{% include 'base_logged.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="/styles/form.css">
{% endblock %}

{% block body %}
    <div class="content modify">
        <div class="overlay"></div>
        <div class="form-container">
            <h2>Ajouter un utilisateur</h2>
            <span class="description">
                <p>Besoin d'ajouter un nouvel utilisateur ?</p>
                <p>Vous pouvez ajouter de nouveaux membres et gérer leurs profils !</p>
            </span>
            {{ form_start(form) }}
            <input type="hidden" name="_token" value="{{ csrf_token('form') }}">
            {{ form_widget(form.email) }}
            {{ form_widget(form.firstName) }}
            {{ form_widget(form.lastName) }}
            {{ form_widget(form.password) }}
            {{ form_widget(form.passwordConfirm) }}
            {{ form_widget(form.pseudo) }}
            {{ form_widget(form.phone_number) }}
            {{ form_widget(form.campus) }}
            {{ form_label(form.profilePicture) }}
            {{ form_widget(form.profilePicture) }}
            <button>Enregistrer</button>
            {{ form_end(form, {'render_rest': false}) }}
        </div>
    </div>
    <script src="/scripts/form.js"></script>
{% endblock %}

templates/user/profileEdit.html.twig
{% include 'base_logged.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="/styles/form.css">
{% endblock %}

{% block body %}
 <div class="content modify">
        <div class="overlay"></div>
        <div class="form-container">
            <h2>Modifier votre profil</h2>
            <span class="description">
                <p>Envie de mettre à jour vos informations personnelles ?</p>
                <p>Personnalisez votre profil pour mieux vous présenter à la communauté du campus !</p>
            </span>
            {{ form_start(form) }}
            <input type="hidden" name="_csrf_token" value="{{ csrf_token('form') }}">
            {{ form_widget(form.pseudo) }}
            {{ form_widget(form.phone_number) }}
            {{ form_widget(form.campus) }}
            {{form_widget(form.lastName)}}
            {{form_widget(form.firstName)}}
            {{form_widget(form.email)}}
            {{form_widget(form.password)}}
            {{form_widget(form.passwordConfirm)}}
            {{form_widget(form.profilePicture)}}
            <button>Enregistrer</button>
            {{ form_end(form) }}
        </div>
    </div>
    <script src="/scripts/form.js"></script>
{% endblock %}

templates/user/profileList.html.twig
{% include 'base_logged.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="/styles/table.css">
{% endblock %}

{% block body %}
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
    <div class="content">
        <span class="flex-center">
        <h2>Listes des utilisateurs</h2>
        <div class="separator"></div>
        </span>
        <main>
            <table>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Profil</th>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Roles</th>
                    <th>Téléphone</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <a href="{{ path('app_profile_view', {'id' : user.id}) }}">
                        {% if user.isActive != true %}
                        <tr style="background-color: #ded8d7">
                            {% else %}
                        <tr>
                            {% endif %}
                            <td data-label="ID">{{ user.id }}</td>
                            <td data-label="Profil" class="profil"><img src="/profilePictures/{{ user.fileName }}"
                                                                        alt=""/>{{ user.pseudo }}</td>
                            <td data-label="Prénom" class="textcenter">{{ user.firstName }}</td>
                            <td data-label="Nom">{{ user.lastName }}</td>
                            <td data-label="Roles">{{ user.roles|join(", ") }}</td>
                            <td data-label="Téléphone">{{ user.phoneNumber }}</td>
                    </a>
                    <td data-label="Action"><a href="{{ path('app_user_delete', {'id' : user.id}) }}" class="action"><i
                                    class="hover-fa fa-solid fa-trash"></i></a><a
                                href="{{ path('app_user_desactivate', {'id' : user.id}) }}"><i
                                    class="hover-fa fa-solid fa-user-xmark"></i></a>
                        <a
                                href="{{ path('app_profile_view', {'id' : user.id}) }}"><i
                                    class="fa-solid fa-user"></i></a>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </main>
        <div class="button-container">
            <a class="action-click" href="{{ path('app_user_create') }}">
                <button class="action-button"><i class="fa-solid fa-user-plus"></i> Ajouter un utilisateur</button>
            </a>
            <a class="action-click" href="{{ asset('csv/sample-data.csv') }}">
                <button class="action-button"><i class="fa-solid fa-file-arrow-down"></i> Télécharger la template CSV
                </button>
            </a>
            <a class="action-click" href="#">
                <button class="action-button"><i class="fa-solid fa-file-arrow-down"></i>
                    {{ form_start(form,{'attr': {'id': 'fileName'}}) }}

                    {{ form_label(form.fileName) }}
                    <div style="display: none">
                        {{ form_widget(form.fileName) }}
                    </div>
                    {{ form_end(form) }}
                </button>
            </a>
            <div class="file_label">

            </div>

        </div>

    </div>
    <script src="/scripts/form.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            // Get the file input element
            var fileInput = document.querySelector('#fileName input[type="file"]');

            if (fileInput) {
                fileInput.addEventListener('change', function () {
                    // Submit the form when a file is selected
                    document.getElementById('fileName').submit();
                });
            }
        });
    </script>

{% endblock %}  

templates/user/profileView.html.twig
{% include 'base_logged.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="/styles/home.css">
    <link rel="stylesheet" href="/styles/profil.css">
{% endblock %}

{% block body %}
<div class="myContent">
    <div class="box">
        <h2>Informations de {{user.pseudo}}</h2>
        <div class="separator"></div>
        <img src="{{ asset('profilePictures/'~ user.fileName) }}" class="profilPicture" alt="ProfilePicture">
        <p class="text title">{{user.pseudo}}</p>
        <p class="text email">{{user.email}}</p>
        <div class="more-information">
            <h2>Plus d’information</h2>
            <div class="separator"></div>
            <div class="myInformation">
                <p><span class="information-title">Téléphone : </span>{{user.phoneNumber}}</p>
                <p><span class="information-title">Campus : </span>{{user.campus.name}}</p>
            </div>
            <div class="myInformation">
                <p><span class="information-title">Nom : </span>{{user.lastName}}</p>
                <p><span class="information-title">Prénom : </span>{{user.firstName}}</p>
            </div>
        </div>  
    </div>
    <div class="box right">
        <h2>Activitées proposé par {{user.pseudo}}</h2>
        <div class="separator"></div>
        <div class="activity-content" id="activityContent">
            {% for activity in activities %}
                {% if activity.state.id != 6 and activity.state.id != 1 %}
                <div class="activity" data-lat="{{ activity.lieu.latitude }}" data-long="{{ activity.lieu.longitude }}" data-id="{{ activity.id }}">
                    <span class="flex">
                        <img src={{ asset('thumbnails/' ~ activity.fileName) }} alt="activity thumbnails"/>
                        <span class="title-description">
                            <p class="title">{{ activity.name }}</p>
                            <p class="description">{{ activity.description }}</p>
                        </span>
                    </span>
                    <span class="information">
                        <span class="information_text">
                            <p>Date limite d'inscription : {{ activity.registrationDateLimit|date('Y-m-d') }}</p>
                            <p>Nombre de places : {{ activity.nbLimitParticipants - activity.registered|length }}</p>
                        </span>
                        <span class="state">
                            {% if activity.state.code == "ACT_CR" %}
                                <button class="status" disable><i class="fa-solid fa-check"></i> Créée</button>
                            {% endif %}
                            {% if activity.state.code == "ACT_INS" %}
                                <button class="status" disable><i class="fa-solid fa-check"></i> Inscription</button>
                            {% endif %}
                            {% if activity.state.code == "ACT_INS_F" %}
                                <button class="status" disable><i class="fa-solid fa-ban"></i> Inscription Fermé</button>
                            {% endif %}
                            {% if activity.state.code == "ACT_EN_C" %}
                                <button class="status" disable><i class="fa-solid fa-bars-progress"></i> En cours</button>
                            {% endif %}
                            {% if activity.state.code == "ACT_INS_F" %}
                                <button class="status status-close" disable><i class="fa-solid fa-circle-xmark"></i> Fermée</button>
                            {% endif %}
                            {% if activity.state.code == "ACT_TER" %}
                                <button class="status status-cancel" disable><i class="fa-solid fa-hourglass-end"></i> Terminée</button>
                            {% endif %}
                            {% if activity.state.code == "ACT_ANN" %}
                                <button class="status status-cancel" disable><i class="fa-solid fa-ban"></i> Annulée</button>
                            {% endif %}
                        </span>
                    </span>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}